grupp_projekt/models.py
import datetime
from app import db

message_recv = db.Table('message_recv',
                        db.Column('user_id', db.Integer, db.ForeignKey('user.id'), primary_key=True),
                        db.Column('message_id', db.Integer, db.ForeignKey('message.id'), primary_key=True)
                        )


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(150))
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(100))
    admin = db.Column(db.BOOLEAN, default=False)
    online = db.Column(db.BOOLEAN, default=False)
    sent_messages = db.relationship('Message', backref='sender', lazy=True)
    recv_messages = db.relationship('Message', secondary=message_recv, lazy='subquery',
                                    backref=db.backref('receivers', lazy=True))

    def is_active(self):
        return True

    def is_authenticated(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return self.id


class Message(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(250))
    body = db.Column(db.Text)
    read = db.Column(db.BOOLEAN, default=False)
    sent_time = db.Column(db.DateTime, default=datetime.datetime.now())
    sender_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

grupp_projekt/app.py
import dotenv
from flask import Flask, render_template, request, redirect, url_for
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


# We will use a factory function to avoid cyclic imports
def create_app():
    app = Flask(__name__)
    # Many parts of flask will require use to use a secret key so we create one
    app.config['SECRET_KEY'] = '123secret'
    # Turn off SqlAlchemy warning
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    # Will configure SQLAlchemy to use SQLite and the file db.sqlite
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite'

    # Init the SQLAlchemy object with our app object
    db.init_app(app)

    # Handle flask-login stuff

    # Create a login manager for flask-login
    login_manager = LoginManager()

    # Init the login manager with our app object
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        from models import User
        return User.query.filter_by(id=user_id).first()

    from blueprints.open import bp_open
    app.register_blueprint(bp_open)

    from blueprints.user import bp_user
    app.register_blueprint(bp_user)

    from blueprints.api import bp_api
    app.register_blueprint(bp_api, url_prefix='/api/v1.0')

    return app


if __name__ == '__main__':
    dotenv.load_dotenv()
    app = create_app()
    app.run()

grupp_projekt/blueprints/api/__init__.py
import json
from functools import wraps
import os

from flask import Blueprint, Response, request
from controllers import user_controller
bp_api = Blueprint('bp_api', __name__)


def authorize(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        api_key = os.environ.get('API_KEY')
        provider_key = request.headers.get('x-api-key', None)
        if provider_key != api_key:
            response = {
                'Result': 'Api key Error',
                'Reson': 'No or wrong api key provided'
            }
            return Response(json.dumps(response), 401, content_type='application/json')
        return f(*args, **kwargs)
    return wrapper


@bp_api.get('/users')
@authorize
def get_all_users():
    users = user_controller.get_all_user()
    cleaned_users = []
    for user in users:
        u = user.__dict__
        del u['_sa_instance_state']
        del u['recv_messages']
        cleaned_users.append(u)

    return Response(json.dumps(cleaned_users), 200, content_type='application/json')

@bp_api.get('/hepp')
@authorize
def hepp_get():
    return "hepp"

grupp_projekt/blueprints/open/__init__.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user

from models import User
from passlib.hash import argon2

bp_open = Blueprint('bp_open', __name__)


@bp_open.get('/')
def index():
    return render_template('index.html')


@bp_open.get('/login')
def login_get():
    return render_template('login.html')


@bp_open.post('/login')
def login_post():
    email = request.form['email']
    password = request.form['password']
    user = User.query.filter_by(email=email).first()
    if user is None:
        flash('Wrong email or password')
        return redirect(url_for('bp_open.login_get'))

    if not argon2.verify(password, user.password):
        flash('Wrong email or password')
        return redirect(url_for('bp_open.login_get'))

    # User is verified. Login in user!
    login_user(user)
    user.online = True

    from app import db
    db.session.commit()
    return redirect(url_for('bp_user.user_get'))


@bp_open.get('/signup')
def signup_get():
    return render_template('signup.html')


@bp_open.post('/signup')
def signup_post():
    name = request.form['name']
    email = request.form.get('email')
    password = request.form['password']
    hashed_password = argon2.using(rounds=10).hash(password)

    # Check if user with this password exists in the database
    user = User.query.filter_by(email=email).first()  # First will give us an object if user exist, or None if not
    if user:
        # If user is not none, then a user with this email exists in the database
        flash("Email address is already in use")
        return redirect(url_for('bp_open.signup_get'))

    new_user = User(name=name, email=email, password=hashed_password)

    from app import db
    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for('bp_open.login_get'))

grupp_projekt/blueprints/user/__init__.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import logout_user, login_required, current_user

from controllers.message_controller import create_message, get_user_messages
from controllers.user_controller import get_all_users, get_user_by_id

bp_user = Blueprint('bp_user', __name__)


@bp_user.get('/profile')
@login_required
def user_get():
    users = get_all_users()
    return render_template('user.html', users=users)


@bp_user.get('/logout')
def logout_get():
    user = current_user
    user.online = False

    from app import db
    db.session.commit()
    logout_user()
    return redirect(url_for('bp_open.index'))


@bp_user.get('/message/<user_id>')
def message_get(user_id):
    user_id = int(user_id)
    receiver = get_user_by_id(user_id)
    return render_template('message.html', receiver=receiver)


@bp_user.post('/message')
def message_post():
    title = request.form['title']
    body = request.form['body']
    receiver_id = request.form['user_id']
    print(title)
    create_message(title, body, receiver_id)
    return redirect(url_for('bp_user.user_get'))


@bp_user.get('/mailbox')
def mailbox_get():
    messages = get_user_messages()
    return render_template('mailbox.html', messages=messages)

grupp_projekt/controllers/message_controller.py
from flask_login import current_user

from controllers.user_controller import get_user_by_id


def create_message(title, body, receiver_id):
    from models import Message
    user = current_user
    message = Message(title=title, body=body, sender_id=user.id)

    receiver_id = int(receiver_id)
    receiver = get_user_by_id(receiver_id)
    message.receivers.append(receiver)
    from app import db
    db.session.add(message)
    db.session.commit()


def get_user_messages():
    return current_user.recv_messages

grupp_projekt/controllers/user_controller.py
from flask_login import current_user


def get_all_users():
    from models import User
    user = current_user
    return User.query.filter(User.id != user.id).all()


def get_user_by_id(user_id):
    from models import User
    return User.query.filter(User.id == user_id).first()

grupp_projekt/templates/base-template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />

</head>
<body>
    <a class="menu-item" href="{{ url_for('bp_open.index') }}">
        Home
    </a>
    {% if current_user.is_authenticated %}
        <a class="menu-item" href="{{ url_for('bp_user.user_get') }}">
            Profile
        </a>
        <a class="menu-item" href="{{ url_for('bp_user.mailbox_get') }}">
            Mailbox
        </a>
        <a class="menu-item" href="{{ url_for('bp_admin.get_admin') }}">
            Admin
        </a>
        <a class="menu-item" href="{{ url_for('bp_user.logout_get') }}">
            Log Out
        </a>
        <a href="{{ url_for('bp_user.mailbox_get') }}">
            <i class="fa fa-fw fa-envelope-open" id="message-symbol"></i>
                <span class="sup" id="message-count"></span>
        </a>
    {% else %}
        <a class="menu-item" href="{{ url_for('bp_open.signup_get') }}">
            Sign Up
        </a>
        <a class="menu-item" href="{{ url_for('bp_open.login_get') }}">
            Log In
        </a>
     {% endif %}

    <hr />
    {% block content %}
    {% endblock %}
     {% if current_user.is_authenticated %}
    <script>
        checkMessages();
        setInterval(checkMessages, 50);

        function checkMessages() {
            fetch("http://127.0.0.1:5010/get_message_count")
                .then(response => response.json())
                .then(msgCount => {
                    let messageSymbol = document.getElementById("message-symbol");
                    let messageCount = document.getElementById("message-count");
                    if(msgCount.unreadMessageCount === 0) {
                        messageSymbol.classList.remove("fa-envelope");
                        messageSymbol.classList.add("fa-envelope-open");
                        messageSymbol.classList.remove("new-msg");
                        messageSymbol.classList.add("no-new-msg");
                        messageCount.innerHTML = "";
                    }
                    else {
                        messageSymbol.classList.remove("fa-envelope-open");
                        messageSymbol.classList.add("fa-envelope");
                        messageSymbol.classList.remove("no-new-msg");
                        messageSymbol.classList.add("new-msg");
                        messageCount.innerHTML = msgCount.unreadMessageCount;
                    }
                });
        }
    </script>
{% endif %}
    {% block scripts %}
    {% endblock %}
</body>
</html>

grupp_projekt/templates/index.html
{% extends "base-template.html" %}

{% block title %}
    Main Page
{% endblock %}

{% block content %}
    <h1>This is the main page</h1>
    <p> the chat application </p>
{% extends "base-template.html" %}

{% block title %}
    Main Page
{% endblock %}

{% block content %}
    <h1>This is the main page</h1>

{% endblock %}




{% endblock %}

grupp_projekt/templates/login.html
{% extends "base-template.html" %}

{% block content %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification">
                {{ messages[0] }}.</a>
            </div>
        {% endif %}
    {% endwith %}
    <form action="{{ url_for('bp_open.login_post') }}" method="POST">

        <input type="email" name="email" placeholder="Your email address" /> <br />
        <input type="password" name="password" placeholder="Enter password" /> <br />

        <input type="submit" value="Log In">

    </form>
{% endblock %}

grupp_projekt/templates/mailbox.html
{% extends "base-template.html" %}

{% block title %}
    Mailbox for {{ current_user.name }}
{% endblock %}

{% block content %}
    <h1 id="main-heading">Mailbox</h1>

    <table>
        <tr>
            <th>From:</th>
            <th>Sent:</th>
            <th>Title:</th>
            <th>Message</th>
        </tr>
        {% for message in messages %}
            <tr>
                <td>{{ message.sender.name }}</td>
                {% if message.sent_time is not none %}
                    <td>{{ message.sent_time.year }}-{{ message.sent_time.month }}-{{ message.sent_time.day }}</td>
                {% else %}
                    <td>-</td>
                {% endif %}
                <td>{{ message.title }}</td>
                <td>{{ message.body }}</td>
            </tr>
        {% endfor %}
    </table>

    <div>
     <br /> <br />
    <h2>Upload your private Rsa-Key to read your messages.</h2>
    <input type="file" id="priv-file" enctype="multipart/form-data" />
    <button type="button" onclick="readPrivateKey()">Upload private Rsa-Key</button><span id="priv-loaded"></span>

    <br /> <br />
    <button onclick="rsaDecrypt()">Decrypt the Message</button>
    <p id="decrypted"></p>
    <br /> <br />
    <br /> <br />
    <input type="text" placeholder="Krypterat meddelande RSA" />
      <br />
    <input type="text" placeholder="Krypterat meddelande AES" />
    <input type="text" placeholder="AES-key" /> <br />
    <input type="text" placeholder=" Meddelandet " /> <br />

    <script src="../static/js/rsa.js"></script>
         let privateKey;

        function readPrivateKey() {
            let files = document.getElementById("priv-file").files;
            let file = files[0];
            let reader = new FileReader();

            reader.onloadend = function (event) {
                privateKey = event.target.result;
                privateKey = privateKey.replace(/(\r\n|\n|\r)/gm, "");
                document.getElementById("priv-loaded").innerHTML = "Private key loaded";
            };

            reader.readAsText(file);
        }


        function rsaDecrypt() {

            let cipher = document.getElementById("encrypted").innerHTML;

            let rsaEncrypt = new JSEncrypt();

            rsaEncrypt.setPrivateKey(privateKey);

            let plainText = rsaEncrypt.decrypt(cipher);

            document.getElementById("decrypted").innerHTML = plainText;
        }
    </script>

    </div>

{% endblock %}

grupp_projekt/templates/message.html
{% extends "base-template.html" %}

{% block title %}
    Send a Message
{% endblock %}

{% block content %}
    <h1>Sending a message to {{ receiver.name }}</h1>
    <form action="{{ url_for('bp_user.message_post') }}" method="POST">
        <input type="text" name="title" placeholder="Message Title" /> <br />
        <input type="hidden" name="user_id" value="{{ receiver.id }}">
        <textarea name="body" placeholder="Message Body"></textarea> <br />
        <input class="send-button" type="submit" value="Send" />
    </form>
{% endblock %}

% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.0.0/crypto-js.min.js"></script>
    <script src="{{ url_for('static', filename='js/rsa.js') }}"></script>

    <script>
    function encryptMessage() {
        let aesKey = key = CryptoJS.lib.WordArray.random(16).toString();

        let rsaEncrypt = new JSEncrypt();
        let publicKey = document.getElementById("user-pubkey").value;

        let message = {
            title: document.getElementById("title").value,
            body: document.getElementById("body").innerHTML
        }

        let msgJson = JSON.stringify(message);

        let encryptedMessage = CryptoJS.AES.encrypt(msgJson, aesKey);

        rsaEncrypt.setPublicKey(publicKey);

        let encryptedAESKey = rsaEncrypt.encrypt(aesKey);

        let msgToSend = {
            receiverId: document.getElementById("user-id").value,
            encryptedMessage: encryptedMessage.toString(),
            encryptedKey: encryptedAESKey.toString()
        }

        let jsonStrToSend = JSON.stringify(msgToSend);
        fetch('http://127.0.0.1:5010/message', {
            method: "POST",
            headers: {
                "Content-type": "application/json"
            },
            body: jsonStrToSend
        }).then(()=>{
            location.href='/profile';
        });

    }

    </script>

{% endblock %}

grupp_projekt/templates/signup.html
{% extends "base-template.html" %}

{% block content %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification">
                {{ messages[0] }}. Go to <a href="{{ url_for('bp_open.login_get') }}">login page</a>
            </div>
        {% endif %}
    {% endwith %}
    <form action="{{ url_for('bp_open.signup_post') }}" method="POST">
        <input type="text" name="name" placeholder="Enter your full name" /> <br />
        <input type="email" name="email" placeholder="Your email address" /> <br />
        <input type="password" name="password" placeholder="Enter password" /> <br />

        <input type="submit" value="Sign Up">

    </form>
{% endblock %}

grupp_projekt/templates/user.html
{% extends "base-template.html" %}

{% block title %}
    User Page
{% endblock %}

{% block content %}
    <h1 id="main-heading">User Page</h1>
    <p>Hello {{ current_user.name }}</p>

    <table>
        <tr>
            <th>User Name</th>
            <th>User Email</th>
            <th>Online</th>
        </tr>
        {% for user in users %}
            <tr>
                <td><a href="{{ url_for('bp_user.message_get', user_id=user.id) }}">{{ user.name }}</a></td>
                <td>{{ user.email }}</td>
                <td class="center-content">
                    {% if user.online %}
                        <div class="circle online"></div>
                    {% else %}
                        <div class="circle offline"></div>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}